"""all-models

Revision ID: 18262409b442
Revises: 0fd90774e0c2
Create Date: 2026-04-17 22:37:55.531728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18262409b442'
down_revision: Union[str, Sequence[str], None] = '0fd90774e0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gesture_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gesture_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_frame_index', sa.Integer(), nullable=False),
    sa.Column('end_frame_index', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('gesture_class_id', sa.Integer(), nullable=False),
    sa.Column('gesture_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gesture_class_id'], ['gesture_classes.id'], ),
    sa.ForeignKeyConstraint(['gesture_type_id'], ['gesture_types.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('landmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('video_processing_tasks')
    op.add_column('videos', sa.Column('filepath', sa.String(), nullable=False))
    op.drop_column('videos', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('videos', 'filepath')
    op.create_table('video_processing_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('video_processing_tasks_video_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('video_processing_tasks_pkey'))
    )
    op.drop_table('landmarks')
    op.drop_table('clips')
    op.drop_table('gesture_types')
    op.drop_table('gesture_classes')
    # ### end Alembic commands ###
